/* eslint-disable @typescript-eslint/no-unused-vars */
export const machines: string[] = ['May001', 'May002', 'May003', 'May004', 'May005', 'May006']

export const firstNames: string[] = [
  'Trần ',
  'Nguyễn ',
  'Vũ ',
  'Phạm ',
  'Lại ',
  'Đoàn ',
  'Đỗ ',
  'Lê ',
  'Tống '
]

export const lastNames: string[] = [
  'Uyên',
  'Lan',
  'Tùng',
  'Quân',
  'Minh',
  'Hiệp',
  'Hải',
  'Ngọc',
  'Hoài',
  'Hà',
  'Diện',
  'Dung',
  'Sơn',
  'Linh',
  'Phương',
  'Loan',
  'Liên'
]

export const middleNames: string[] = [
  'Hồng ',
  'Vũ Đình ',
  'Thanh ',
  'Ngọc Minh ',
  'Phương ',
  'Ngọc Bích ',
  'Minh ',
  'Thanh Sơn ',
  'Phạm Đình Thái ',
  'Trần Xuân Diệu ',
  'Ngọc Linh ',
  'Vũ Phạm Đình Tài '
]
export const detailXa: string[] = [
  'Xóm 1',
  'Xóm 2',
  'Xóm 3',
  'Xóm 4',
  'Xóm 5',
  'Xóm 6',
  'Xóm 7',
  'Xóm 8',
  'Xóm 9',
  'Xóm 10',
  'Xóm 11',
  'Xóm 12'
]

export const provinces: string[] = [
  'Hà Nội',
  'Lào Cai',
  'Điện Biên',
  'Lai Châu',
  'Sơn La',
  'Yên Bái',
  'Hoà Bình',
  'Thái Nguyên',
  'Hà Giang',
  'Lạng Sơn',
  'Quảng Ninh',
  'Bắc Giang',
  'Phú Thọ',
  'Vĩnh Phúc',
  'Bắc Ninh',
  'Hải Dương',
  'Hải Phòng',
  'Hồ Chí Minh',
  'Thừa Thiên Huế'
]

export const districts: string[] = [
  'Ba Vì',
  'Long Biên',
  'Hà Đông',
  'Thanh Trì',
  'Gia Lâm',
  'Bắc Từ Liêm',
  'Nam Từ Liêm',
  'Cầu Giấy',
  'Đống Đa',
  'Hai Bà Trưng',
  'Hoàn Kiếm',
  'Hoàng Mai',
  'Tây Hồ',
  'Thanh Xuân',
  'Nậm Nhùn',
  'Quỳnh Nhai',
  'Thuận Châu',
  'Mường La',
  'Bắc Yên',
  'Phù Yên',
  'Mộc Châu',
  'Yên Châu',
  'Mai Sơn',
  'Sông Mã',
  'Sốp Cộp',
  'Vân Hồ',
  'Thành phố Yên Bái',
  'Nguyễn Trung Trực'
]

export const communes: string[] = [
  'Hàng Bạc',
  'Ngô Thì Nhậm',
  'Phạm Đình Hổ',
  'Lạc Nông',
  'Tân Xã',
  'Thạch Xá',
  'Bình Phú',
  'Hạ Bằng',
  'Đồng Trúc',
  'Phụng Châu',
  'Tiên Phương',
  'Đông Sơn',
  'Phú Nam',
  'Đông Phương Yên',
  'Phú Nghĩa',
  'Trường Yên',
  'Ngọc Hòa',
  'Thủy Xuân Tiên',
  'Thanh Bình',
  'Trung Hòa',
  'Đại Yên',
  'Thụy Hương',
  'Yên Cường',
  'Minh Cường',
  'Thàng Tín',
  'Hồng Minh',
  'Phượng Dực',
  'Văn Nhân',
  'Thụy Phú',
  'Tri Trung',
  'Đại Thắng',
  'Phú Túc',
  'Trần Nguyên Hãn',
  'Dịch Vong Hậu',
  'Vĩnh Tuy',
  'An Khánh'
]

export const stress: string[] = [
  'Minh Khai',
  'Võ Thị Sáu',
  'Nguyễn Du',
  'Bùi Thị Xuân',
  'Ngô Thì Nhậm',
  'Nguyễn Tuân',
  'Nguyễn Trãi',
  'Hàng Đào',
  'Duy Tân',
  'Xuân Thủy',
  'Trần Thái Tông',
  'Trần Xuân Phái',
  'Pham văn Đồng',
  'Lý Thái Tổ',
  'ĐT 72',
  'KĐT An Khánh',
  'Hàng Bài'
]

export const genders: string[] = ['Nam', 'Nữ']

export const features: string[] = [
  'Nốt ruồi 1cm trên sau cánh',
  'Nốt ruồi c 1cm trên sau đuôi',
  'Sẹo chấm c 1cm sau đuôi',
  'Nốt ruồi c 1cm dưới sau đầu',
  'Nốt ruồi cách 2 cm dưới',
  'Nốt ruồi cách 1 cm dưới'
]

export const positions: string[] = [
  'mắt phải',
  'cánh mũi phải',
  'mép phải',
  'mép trái',
  'mắt trái',
  'lông mày trái',
  'lông mày phải'
]

export const nations: string[] = [
  'Kinh',
  'Tày',
  'Thái',
  'Hoa',
  'Khơ Mú',
  'Mường',
  'Nùng',
  "H'Mông",
  'Dao',
  'Gia Rai',
  'Ê Đê',
  'Ba Na',
  'Xơ Đăng',
  'Sán Chay',
  'Cơ Tu',
  'Chăm',
  'Sán Dìu',
  'Ra Glai',
  "M'Nông",
  'Thổ',
  'Xtiêng',
  'Bru-Vân Kiều',
  'Cơ Ho',
  'Giáy',
  'Tà Ôi',
  'Mạ',
  'Co',
  'Chơ Ro',
  'Hrê',
  'Xinh Mun',
  'Chu Ru',
  'Lào',
  'Kháng',
  'La Chí',
  'La Ha',
  'Phù Lá',
  'La Hủ',
  'Lự',
  'Ngái',
  'Pà Thẻn',
  'Chứt',
  'La',
  'Ơ Đu',
  'Bố Y',
  'Rơ Măm',
  'Brâu',
  'Ước',
  'Hà Nhì',
  'Cống',
  'Si La',
  'Pu Péo',
  'Rơ Ngao',
  'Co Lao',
  'Tà Ê Đăng',
  'Khơ Me',
  'Cờ Lao',
  'La Hu',
  'Lô Lô',
  'Phù Lá',
  'Si La',
  'La Chí',
  'La Ha',
  'Chứt'
]

export const religions: string[] = [
  'Phật giáo',
  'Công giáo',
  'Hồi giáo',
  'Tin lành',
  'Cao Đài',
  'Đạo Bửu Sơn Kỳ Hương',
  'Tứ Ân Hiếu Nghĩa',
  'Đạo Dừa',
  "Bahá'í",
  'Đạo Tam Kỳ Phổ Độ',
  'Tịnh Độ Cư Sĩ',
  'Minh Sư Đạo',
  'Chí Hoái Đạo',
  'Hòa Hảo',
  'Phật Âm',
  'Hộ Pháp',
  'Đạo Tràng Thiên Vương',
  'Hiệp Thiên Đài',
  'Đạo An Nam Ông',
  'Đạo Minh Đức'
]
export const placeOfBirth: string[] = [
  'Hà Nội',
  'Hồ Chí Minh',
  'Đà Nẵng',
  'Hải Phòng',
  'Cần Thơ',
  'Huế',
  'Nha Trang',
  'Vũng Tàu',
  'Đà Lạt',
  'Hội An',
  'Phú Quốc',
  'Sapa',
  'Quy Nhơn',
  'Đồng Hới',
  'Buôn Ma Thuột',
  'Thanh Hóa',
  'Ninh Bình'
]
